### ISSUE TITLE
TypeError on Line 219: Unexpected Keyword Argument 'token'

### ISSUE THREAD

**Issue by newcoder0007** [can-kat/crypto-wallet-tracker#1] opened 2023-05-27 04:57 UTC
While using the script found in the "crypto-wallet-tracker/main.py" file, I encountered a TypeError on line 219. The error message indicated that the Updater.__init__() method received an unexpected keyword argument 'token'.
The error message :`/crypto-wallet-tracker/main.py", line 219, in <module>
    updater = Updater(token=TELEGRAM_BOT_TOKEN, use_context=True)
TypeError: Updater.__init__() got an unexpected keyword argument 'token'`
The TypeError is raised because the 'token' keyword argument is not expected or is not properly handled in the __init__() method of the Updater class. This issue is preventing me from proceeding further with the script execution.

To assist with troubleshooting, could you kindly clarify if there have been recent updates or changes to the Updater class that might have removed or renamed the 'token' parameter? I'm using the latest version of your script and all dependencies are up to date.

Thank you for your help!

**Comment by can-kat** [comment] 2023-05-29 01:34
Hello,

The issue is about `python-telegram-bot` lib version. You must be using 13.7 please follow up these commands in terminal:

`pip uninstall python-telegram-bot`

`pip install python-telegram-bot==13.7`

You issue should be fixed now, if it doesn't please let me know!

**Closed** 2023-06-18 17:54 UTC
